/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoio;

import java.io.BufferedReader;
import java.util.ArrayList;
import javax.swing.JPanel;
import proyectoio.Tiempo;
import proyectoio.Servidor;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;

/**
 *
 * @author juan_
 */
public class Formulario extends javax.swing.JFrame  {

    
        int tiempoSimulacion;
        int cantClientes;
        int cantServidores = 0;
        int tablaEventos;
        int costoEspera = 0;
        int cantValores;
        int costoServidor = 0;
        int tiempoTotal = 0;
        
        
        ArrayList<Tiempo> tiemposServicios = new ArrayList<>();
        
        ArrayList<ArrayList<Tiempo>> tiemposLlegada = new ArrayList<ArrayList<Tiempo>>();
         
    
    
    public Formulario() {
        initComponents();
        tiemposLlegada.add( new ArrayList<Tiempo>());
        tiemposLlegada.add( new ArrayList<Tiempo>());
        tiemposLlegada.add( new ArrayList<Tiempo>());
        tiemposLlegada.add( new ArrayList<Tiempo>());
        tiemposLlegada.add( new ArrayList<Tiempo>());
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        clientesPermitidosSelector1 = new javax.swing.JSpinner();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        TablaEventos = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        unidadTiempoSelector = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        AgregaTLLP = new javax.swing.JButton();
        AgregaTSP = new javax.swing.JButton();
        costoServidorTextField = new javax.swing.JSpinner();
        cantidadServidoresSelector = new javax.swing.JSpinner();
        costoEsperaTextField = new javax.swing.JSpinner();
        tiempoSimulacionCampoText = new javax.swing.JSpinner();
        clientesPermitidosSelector = new javax.swing.JSpinner();
        tiempoLLP = new javax.swing.JTextField();
        probSP = new javax.swing.JTextField();
        probLLP = new javax.swing.JTextField();
        tiempoSP = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        diaTiempoLlegadaSelector = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        generarArchivo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Volver al formulario");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17mostrarFormulario(evt);
            }
        });

        clientesPermitidosSelector1.setToolTipText("");
        clientesPermitidosSelector1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clientesPermitidosSelector1.setValue(2);

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\juan_\\OneDrive\\Escritorio\\Segunda Entrega IO\\ProyectoIO\\images\\bbva-logo.png")); // NOI18N

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));

        TablaEventos.setBackground(new java.awt.Color(238, 238, 238));
        TablaEventos.setEditable(true);
        TablaEventos.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        TablaEventos.setForeground(new java.awt.Color(102, 102, 102));
        TablaEventos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Si" }));
        TablaEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TablaEventosActionPerformed(evt);
            }
        });

        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        unidadTiempoSelector.setBackground(new java.awt.Color(238, 238, 238));
        unidadTiempoSelector.setEditable(true);
        unidadTiempoSelector.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        unidadTiempoSelector.setForeground(new java.awt.Color(102, 102, 102));
        unidadTiempoSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minutos", "Horas", "Días", "Semanas", "Meses", "Años" }));
        unidadTiempoSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadTiempoSelectorActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("1.- Selecciona la unidad de tiempo ");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("4.- Cantidad de servidores");

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Servidores");

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("5.- Costo de cada servidor");

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("$/Min");

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("6.- Costo de espera por cliente");

        jLabel19.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("$/Min");

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("1.- Selecciona la unidad de tiempo ");

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("2.- Tiempo total de simulacion");

        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Unidad Tiempo");

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("3.- Clientes permitidos en el sistema");

        jLabel22.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Clientes");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("9.- Tiempo de servicio y probabilidad");

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel24.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("8.- Tiempo de llegada y probabilidad (Lunes a Viernes)");

        AgregaTLLP.setText("Agregar");
        AgregaTLLP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregaTLLPActionPerformed(evt);
            }
        });

        AgregaTSP.setText("Agregar");
        AgregaTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregaTSPActionPerformed(evt);
            }
        });

        tiempoLLP.setText("0");

        probSP.setText("0.0");
        probSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                probSPActionPerformed(evt);
            }
        });

        probLLP.setText("0.0");

        tiempoSP.setText("0");

        jButton2.setText("Cargar Archivo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        diaTiempoLlegadaSelector.setBackground(new java.awt.Color(238, 238, 238));
        diaTiempoLlegadaSelector.setEditable(true);
        diaTiempoLlegadaSelector.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        diaTiempoLlegadaSelector.setForeground(new java.awt.Color(102, 102, 102));
        diaTiempoLlegadaSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes" }));
        diaTiempoLlegadaSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaTiempoLlegadaSelectorActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("11.- Generar Archivo");

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("10.- Tabla de eventos");

        generarArchivo.setBackground(new java.awt.Color(238, 238, 238));
        generarArchivo.setEditable(true);
        generarArchivo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        generarArchivo.setForeground(new java.awt.Color(102, 102, 102));
        generarArchivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Si" }));
        generarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unidadTiempoSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(cantidadServidoresSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(costoServidorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(clientesPermitidosSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(tiempoSimulacionCampoText, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(costoEsperaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(104, 104, 104)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TablaEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(diaTiempoLlegadaSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tiempoLLP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(probLLP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(AgregaTLLP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(tiempoSP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(probSP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AgregaTSP, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(generarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AgregaTLLP)
                            .addComponent(tiempoLLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(probLLP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diaTiempoLlegadaSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tiempoSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(probSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgregaTSP))
                        .addGap(64, 64, 64)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TablaEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(generarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel4))
                        .addGap(6, 6, 6)
                        .addComponent(unidadTiempoSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tiempoSimulacionCampoText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel21)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clientesPermitidosSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidadServidoresSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costoServidorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costoEsperaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 38)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Simulacion de cola ");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Sucursal Pzo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel17mostrarFormulario(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17mostrarFormulario
        Formulario formulario = new Formulario();
        formulario.setSize(800,500);
        

    }//GEN-LAST:event_jLabel17mostrarFormulario

    private void unidadTiempoSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadTiempoSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unidadTiempoSelectorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
    ArrayList<Servidor> servidores = new ArrayList<>();
    int UnidadTiempo= unidadTiempoSelector.getSelectedIndex();
    int tiempoTotalSimulacion=(Integer) tiempoSimulacionCampoText.getValue() ; 
    int clientesPermitidos = (Integer) clientesPermitidosSelector.getValue();
    int costoServidor = (Integer) costoServidorTextField.getValue();
    int costoEspera = (Integer) costoEsperaTextField.getValue();
    int EventosTable= TablaEventos.getSelectedIndex();
    int archivoBoolean = generarArchivo.getSelectedIndex();
    
    for(int i=0;i<(Integer) cantidadServidoresSelector.getValue();i++)      
        servidores.add(new Servidor (costoServidor,true));

    Simulacion nueva = new Simulacion (UnidadTiempo,clientesPermitidos, tiemposLlegada,costoServidor, costoEspera, 
           (Integer) cantidadServidoresSelector.getValue(),tiempoTotalSimulacion,servidores,tiemposServicios,EventosTable,archivoBoolean );
    
   
    nueva.Inicio();
    
    setVisible(false);
    
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AgregaTLLPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregaTLLPActionPerformed
       
         
       tiemposLlegada.get(diaTiempoLlegadaSelector.getSelectedIndex()).add(new Tiempo(Integer.parseInt(tiempoLLP.getText()),Float.parseFloat(probLLP.getText())  ,0,0));
        JOptionPane.showMessageDialog(null, "Tiempo de Llegada y Probabilidad Agregado Correctamente");
      
       
       
  
 
        
    }//GEN-LAST:event_AgregaTLLPActionPerformed

    private void probSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_probSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_probSPActionPerformed

    private void AgregaTSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregaTSPActionPerformed
        
        
        tiemposServicios.add(new Tiempo(Integer.parseInt(tiempoSP.getText()),Float.parseFloat(probSP.getText())  ,0,0)) ;
        JOptionPane.showMessageDialog(null, "Tiempo de Servicio y Probabilidad Agregado Correctamente");
        
        
    }//GEN-LAST:event_AgregaTSPActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
        int k=0;
        int UnidadTiempo=0;
        int tiempoTotalSimulacion=0;
        int clientesPermitidos=0;
        int costoServidor=0;
        int costoEspera=0;
        int cantidadServidores=0;
        int eventos=0;
        int archivos= 0;
        ArrayList<Servidor> servidores = new ArrayList<>();

        JFileChooser jf = new JFileChooser ();
        jf.showOpenDialog(this);
        File archivo = jf.getSelectedFile();
       
        
     

      try {

        FileReader fr = new FileReader (archivo);
        BufferedReader br = new BufferedReader(fr);

         String linea;
         while((linea=br.readLine())!=null)  {
             
         if (k==0 ) {

         UnidadTiempo=Integer.parseInt(linea);
  
         } else 
         
         if (k==1) {

             tiempoTotalSimulacion= Integer.parseInt(linea);

         } else if (k==2) {

             clientesPermitidos = Integer.parseInt(linea);

         } else if (k==3) {
 
             cantidadServidores= Integer.parseInt(linea);
         
         } else if (k==4) {
         
             
             costoServidor=Integer.parseInt(linea);
         
         } else if (k==5) {
         
             
             costoEspera=Integer.parseInt(linea);
         
         } else if (k==7) {

             char corchete;
             String valueString="";
             int value;
             String pr0bString="";
             float pr0b;
             int flag=0;
             
             for(int i=8;i<linea.length();i++){
             
                 if (linea.charAt(i)!=';' && linea.charAt(i)!='{' && linea.charAt(i)!=']' ) {
                     
                     if (linea.charAt(i)!=',' && flag==0){
                    
                        valueString=valueString+linea.charAt(i);
                    }if (linea.charAt(i)==','){
                    
                       flag=1;
                    }else if (linea.charAt(i)!='}' && flag==1) {
                    
                       pr0bString=pr0bString+linea.charAt(i);
                    
                    } 
                    
                    if (linea.charAt(i)=='}') {
                    
                        
                        flag=0;
                        i++;
                        
                        
                         tiemposLlegada.get(0).add(new Tiempo(Integer.parseInt(valueString),Float.parseFloat(pr0bString),0,0));
                        valueString="";
                        pr0bString="";
                        
                        

                    }
               
                 }
      
             
             }     
        
             
             
             
             
         
         } else if (k==8) {
         
             char corchete;
             String valueString="";
             int value;
             String pr0bString="";
             float pr0b;
             int flag=0;

             
             for(int i=9;i<linea.length();i++){
             
                 if (linea.charAt(i)!=';' && linea.charAt(i)!='{' && linea.charAt(i)!=']' ) {
                     
                     if (linea.charAt(i)!=',' && flag==0){
                    
                        valueString=valueString+linea.charAt(i);
                    }if (linea.charAt(i)==','){
                    
                       flag=1;
                    }else 
                    if (linea.charAt(i)!='}' && flag==1) {
                    
                       pr0bString=pr0bString+linea.charAt(i);
                    
                    } 
                    
                    if (linea.charAt(i)=='}') {
                    
                        
                        flag=0;
                        i++;
                        
                        
                         tiemposLlegada.get(1).add(new Tiempo(Integer.parseInt(valueString),Float.parseFloat(pr0bString),0,0));
                        valueString="";
                        pr0bString="";
                        
                        

                    }
               
                 }
      
             
             }     
        
         
         }
     
         else if (k==9) {
         
             char corchete;
             String valueString="";
             int value;
             String pr0bString="";
             float pr0b;
             int flag=0;

             
             for(int i=12;i<linea.length();i++){
             
                 if (linea.charAt(i)!=';' && linea.charAt(i)!='{' && linea.charAt(i)!=']' ) {
                     
                     if (linea.charAt(i)!=',' && flag==0){
                    
                        valueString=valueString+linea.charAt(i);
                    }if (linea.charAt(i)==','){
                    
                       flag=1;
                    }else 
                    if (linea.charAt(i)!='}' && flag==1) {
                    
                       pr0bString=pr0bString+linea.charAt(i);
                    
                    } 
                    
                    if (linea.charAt(i)=='}') {
                    
                        
                        flag=0;
                        i++;
                        
                        
                         tiemposLlegada.get(2).add(new Tiempo(Integer.parseInt(valueString),Float.parseFloat(pr0bString),0,0));
                        valueString="";
                        pr0bString="";
                        
                        

                    }
               
                 }
      
             
             }     
        
         
         }
     
         else if (k==10) {

             char corchete;
             String valueString="";
             int value;
             String pr0bString="";
             float pr0b;
             int flag=0;
             
             for(int i=9;i<linea.length();i++){
             
                 if (linea.charAt(i)!=';' && linea.charAt(i)!='{' && linea.charAt(i)!=']' ) {
                     
                     if (linea.charAt(i)!=',' && flag==0){
                    
                        valueString=valueString+linea.charAt(i);
                    }if (linea.charAt(i)==','){
                    
                       flag=1;
                    }else 
                    if (linea.charAt(i)!='}' && flag==1) {
                    
                       pr0bString=pr0bString+linea.charAt(i);
                    
                    } 
                    
                    if (linea.charAt(i)=='}') {
                    
                        
                        flag=0;
                        i++;
                        
                        
                         tiemposLlegada.get(3).add(new Tiempo(Integer.parseInt(valueString),Float.parseFloat(pr0bString),0,0));
                        valueString="";
                        pr0bString="";
                        
                        

                    }
               
                 }
      
             
             }     
        
         
         }
     
         else if (k==11) {

             char corchete;
             String valueString="";
             int value;
             String pr0bString="";
             float pr0b;
             int flag=0;
             
             for(int i=10;i<linea.length();i++){
             
                 if (linea.charAt(i)!=';' && linea.charAt(i)!='{' && linea.charAt(i)!=']' ) {
                     
                     if (linea.charAt(i)!=',' && flag==0){
                    
                        valueString=valueString+linea.charAt(i);
                    }if (linea.charAt(i)==','){
                    
                       flag=1;
                    } else
                    if (linea.charAt(i)!='}' && flag==1) {
                    
                       pr0bString=pr0bString+linea.charAt(i);
                    
                    } 
                    
                    if (linea.charAt(i)=='}') {
                    
                        
                        flag=0;
                        i++;
                        
                        
                         tiemposLlegada.get(4).add(new Tiempo(Integer.parseInt(valueString),Float.parseFloat(pr0bString),0,0));
                        valueString="";
                        pr0bString="";
                        
                        

                    }
               
                 }
      
             
             }     
        
         
         }
     
         
         else if (k==14) {
         
            char corchete;
             String valueString="";
             int value;
             String pr0bString="";
             float pr0b;
             int flag=0;
             
             for(int i=2;i<linea.length();i++){
             
                 if (linea.charAt(i)!=';' && linea.charAt(i)!='{' && linea.charAt(i)!=']' ) {
                     
                     if (linea.charAt(i)!=',' && flag==0){
                    
                        valueString=valueString+linea.charAt(i);
                    }if (linea.charAt(i)==','){
                    
                       flag=1;
                    } else
                    if (linea.charAt(i)!='}' && flag==1) {
                    
                       pr0bString=pr0bString+linea.charAt(i);
                    
                    } 
                    
                    if (linea.charAt(i)=='}') {

                        flag=0;
                        i++;
                        tiemposServicios.add(new Tiempo(Integer.parseInt(valueString),Float.parseFloat(pr0bString),0,0));
                        valueString="";
                        pr0bString="";


                    }
                 }

             }  
         } else if (k==16) {
         
             eventos=Integer.parseInt(linea);
             
         } else if (k==17) {
         
            archivos=Integer.parseInt(linea);
         }

         k++;
         
         }
          fr.close();
      }
      catch(Exception e){
         e.printStackTrace();
      }finally{
         
         try{                    
             
                          
         }catch (Exception e2){ 
            e2.printStackTrace();
         }
      }
        
        
        // acomodar en cada lao mano
      
    
   for(int i=0;i<cantidadServidores;i++)      
        servidores.add(new Servidor (costoServidor,true)); 

    Simulacion nueva = new Simulacion (UnidadTiempo,clientesPermitidos, tiemposLlegada,costoServidor, costoEspera, 
           (Integer) cantidadServidoresSelector.getValue(),tiempoTotalSimulacion,servidores,tiemposServicios,eventos,archivos );
    
   
    nueva.Inicio();  
    
    setVisible(false);
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void diaTiempoLlegadaSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaTiempoLlegadaSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaTiempoLlegadaSelectorActionPerformed

    private void TablaEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TablaEventosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaEventosActionPerformed

    private void generarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generarArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregaTLLP;
    private javax.swing.JButton AgregaTSP;
    public javax.swing.JComboBox<String> TablaEventos;
    private javax.swing.JSpinner cantidadServidoresSelector;
    private javax.swing.JSpinner clientesPermitidosSelector;
    public javax.swing.JSpinner clientesPermitidosSelector1;
    private javax.swing.JSpinner costoEsperaTextField;
    private javax.swing.JSpinner costoServidorTextField;
    public javax.swing.JComboBox<String> diaTiempoLlegadaSelector;
    public javax.swing.JComboBox<String> generarArchivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField probLLP;
    private javax.swing.JTextField probSP;
    private javax.swing.JTextField tiempoLLP;
    private javax.swing.JTextField tiempoSP;
    private javax.swing.JSpinner tiempoSimulacionCampoText;
    public javax.swing.JComboBox<String> unidadTiempoSelector;
    // End of variables declaration//GEN-END:variables
}
